version: '4.15'

# !FOR DEPLOYMENT ONLY
services:
  nextjs:
    build: ./client-web
    ports:
      - '3000:3000'
    volumes:
      - ./client-web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  main-backend:
    build: ./server/main-backend
    ports:
      - '3000:3000'
    volumes:
      - ./client-web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  postgres-db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: alx
      POSTGRES_PASSWORD: serbvn
      POSTGRES_DB: trainerz_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: